<a href="https://colab.research.google.com/github/25wh1a0562-wq/NASSCOM/blob/main/Week2_numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

arr1_1=np.arange(100)
arr1_2=np.ones((3,3))
arr1_3=np.full((2,4),7)
arr1_4=np.random.randint(10,51,(5,5))
print(arr1_1)
print(arr1_2)
print(arr1_3)
print(arr1_4)




--- Task 1: Array Creation Shortcuts ---
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]]
[[28 42 37 22 29]
 [43 16 22 41 17]
 [50 13 21 17 47]
 [41 24 11 24 25]
 [26 36 43 36 14]]


In [8]:
# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

# 2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.
# 2.2 Extract the first row. Store it in 'row2_2'.
# 2.3 Extract the last column. Store it in 'col2_3'.
# 2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.
# 2.5 Using boolean indexing, select all elements in 'data' that are greater than 100. Store them in 'filtered_elements2_5'.
val2_1=data[2,3]
row1_2=data[0]
col2_3 =data[3]
sub_arr2_4=data[1:3,0:2]
filtered_elements2_5=data[data>100]
print(val2_1)
print(row1_2)
print(col2_3)
print(sub_arr2_4)
print(filtered_elements2_5)




--- Task 2: Indexing and Slicing with Arrays ---
120
[10 20 30 40]
[130 140 150 160]
[[ 50  60]
 [ 90 100]]
[110 120 130 140 150 160]


In [9]:
# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5)) # Random 4x5 array with values 1 to 20

# 3.1 Create a new array 'arr3_2' whe

# Your code for Task 3 here:
arr3_1=np.random.randint(1,21,size=(4,5))
arr3_2=np.where(arr3_1<10,0,arr3_1)
even_count3_3=np.sum(arr3_2%2==0)
print(arr3_2)
print(even_count3_3)


--- Task 3: Conditional Operations ---
[[18 19 11  0  0]
 [16 14 13 17 20]
 [ 0  0 11  0 10]
 [10  0 12 13 20]]
14


In [11]:
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])
sum4_1=np.sum(arr4_1)
mean_cols4_3=np.mean(arr4_1,axis=0)
max_rows4_3=np.max(arr4_1,axis=1)
std4_4=np.std(arr4_1)
print("sum of the elements:",sum4_1)
print("mean of each coloumn:",mean_cols4_3)
print("max of each row:",max_rows4_3)
print("standard deviation:",mean_cols4_3)


--- Task 4: Aggregation Functions ---
sum of the elements: 84
mean of each coloumn: [11.          6.66666667 10.33333333]
max of each row: [12 15 20]
standard deviation: [11.          6.66666667 10.33333333]


In [12]:
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23

reshaped_arr5_2=np.arange(24).reshape((4,6))
reshaped_arr5_3=np.arange(24).reshape((2,3,4))
flattened_arr5_4=reshaped_arr5_2.ravel()
print("reshaped_arr5_2:\n",reshaped_arr5_2)
print("reshaped_arr5_3:\n",reshaped_arr5_3)
print("flattened",flattened_arr5_4)


--- Task 5: Reshaping and Flattening ---
reshaped_arr5_2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
reshaped_arr5_3:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
flattened [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [13]:
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.
# 6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.
result6_1=np.array(arr6_1 +scalar)
result6_2=np.array(arr6_1+vector)
print("adding scalar ",result6_1)
print("adding vector",result6_2)


--- Task 6: Broadcasting ---
adding scalar  [[11 12 13]
 [14 15 16]
 [17 18 19]]
adding vector [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [14]:
# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])

view_arr7 = original_arr7.copy()
view_arr7[0]=99
print("original after view change",view_arr7)
copy_arr7=original_arr7.copy()
copy_arr7[4]=0
print("original",copy_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
original after view change [99  2  3  4  5]
original [1 2 3 4 0]


In [15]:
# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])
vstack_arr8_1=np.vstack((arr8_a,arr8_b))
hstack=np.hstack((arr8_a,arr8_b))
combined_arr8_3=np.vstack((vstack_arr8_1,arr8_c))
part1,part2,part3,part4,part5=np.split(combined_arr8_3,5)
print("vstack",vstack_arr8_1)
print("hstack",hstack)
print("combined",combined_arr8_3)
print("split",part1,part2,part3,part4,part5)


--- Task 8: Stacking and Splitting Arrays ---
vstack [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack [[1 2 5 6]
 [3 4 7 8]]
combined [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
split [[1 2]] [[3 4]] [[5 6]] [[7 8]] [[ 9 10]]


In [16]:
# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])
sorted_arr9_1=np.sort(arr9_1)
sorted_cols9_2=np.sort(arr9_2d,axis=1)
idx9_3=np.where(arr9_1==9)
max_idx9_4=np.max(arr9_1)
print("sorting",sorted_arr9_1)
print("coloumn",sorted_cols9_2)
print("index",idx9_3)
print("maximum",max_idx9_4)


--- Task 9: Sorting and Searching ---
sorting [1 2 3 4 5 6 7 8 9]
coloumn [[10 20 30]
 [40 50 60]
 [70 80 90]]
index (array([4]),)
maximum 9
